# Generated by Django 2.2.9 on 2020-02-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
